### ISSUE TITLE
SFML2 sfTransform_Identity doesnt exist.

### ISSUE THREAD

**Issue by Nekroze** [mdparker/Derelict3#71] opened 2012-11-22 01:20 UTC
The blank transform "sfTransform_Identity" defined in Transform.h doesnt seem to exist in derelict3 bindings.

This may be causing issues with using RenderStates.

**Comment by mdparker** [comment] 2012-11-22 03:35
How is it causing issues? sfTransform_Identity is just a const instance of sfTansform that's set to the identity matrix. Declaring an instance in Derelict will do nothing. If you need an identity matrix, you can set one yourself. So I'm not sure what the problem is.

**Comment by Nekroze** [comment] 2012-11-22 08:14
Even Defining my own matrix as suggested above does not work. for more information and even a test case here is my thread of this problem over on the sfml forums http://en.sfml-dev.org/forums/index.php?topic=9767.0

**Comment by mdparker** [comment] 2012-11-22 09:54
OK, a closer look has shown me that the changes to the sfTransform API were not committed to Derelict. My apologies. That has been corrected. I've also added a constant sfTransform_Identity that you can use. Please let me know if you have any more issues with the sfml binding.

**Closed as completed by mdparker** 2012-11-22 09:54 UTC
